from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from bson import ObjectId

# custom ObjectId field becuz pydantic doesnt support it out of the box
class PyObjectId(ObjectId):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not ObjectId.is_valid(v):
            raise ValueError("Invalid ObjectId")  # maybe add more  details later
        return ObjectId(v)

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type="string")  # mongodb ids are strings in  json


# main message model for the chat  service
class Message(BaseModel):
    # TODO: mby add attachments support??
    
    id: Optional[PyObjectId] = Field(alias="_id")  # this is annoyin but mongodb needs _id
    sender_id: int    # FK to users table in  postgres
    receiver_id: int  # same here
    content: str      # actual mesage content
    created_at: datetime = Field(default_factory=datetime.utcnow)  # autogenerated

    class Config:
        # had to google this stuff tbh
        arbitrary_types_allowed = True
        json_encoders = {
            ObjectId: str,  # convert to string cuz json cant handle ObjectId
            datetime: lambda dt: dt.isoformat()  # same for  datetime
        }
        
        # example for  documentation
        schema_extra = {
            "example": {
                "sender_id": 1,      # some random user
                "receiver_id": 2,    # another randm user
                "content": "Hello!",  # basic test msg
                "created_at": datetime.utcnow().isoformat()  # current time
            }
        } 